// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHZRLZEcsBWD8O59p4dRiGFMlLdzreBmQ',
    appId: '1:401721867005:web:a14034b6c68d7b783f9c94',
    messagingSenderId: '401721867005',
    projectId: 'love-ce3d8',
    authDomain: 'love-ce3d8.firebaseapp.com',
    databaseURL: 'https://love-ce3d8-default-rtdb.firebaseio.com',
    storageBucket: 'love-ce3d8.appspot.com',
    measurementId: 'G-NGSL18VCYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8EzyocuK2YqaFcoVw0rANo9w35wIeYHE',
    appId: '1:675051817413:android:8c1dc24cafbc53df99a3ac',
    messagingSenderId: '675051817413',
    projectId: 'love-3af96',
    storageBucket: 'love-3af96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbcNdSFk3SWD8Z2G1saXF173c_jleSaNo',
    appId: '1:675051817413:ios:3f41953d2c0d89c499a3ac',
    messagingSenderId: '675051817413',
    projectId: 'love-3af96',
    storageBucket: 'love-3af96.appspot.com',
    iosClientId: '675051817413-k88i9rgt4gcqutlu6ltdf2ai0afqeoo1.apps.googleusercontent.com',
    iosBundleId: 'com.duytq.flutterchatdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBASOmvgf9bguvFREwSDDo5iwT9kNnlfgc',
    appId: '1:401721867005:ios:26d498236379b59a3f9c94',
    messagingSenderId: '401721867005',
    projectId: 'love-ce3d8',
    databaseURL: 'https://love-ce3d8-default-rtdb.firebaseio.com',
    storageBucket: 'love-ce3d8.appspot.com',
    androidClientId: '401721867005-gvqqnkrcrq2bn7mnt2i7e6ijmrf0bs7d.apps.googleusercontent.com',
    iosClientId: '401721867005-9vvt4k6g2if0usf0e0gjed3kds0f08gj.apps.googleusercontent.com',
    iosBundleId: 'n',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHZRLZEcsBWD8O59p4dRiGFMlLdzreBmQ',
    appId: '1:401721867005:web:6827f3ce0b1a3ae73f9c94',
    messagingSenderId: '401721867005',
    projectId: 'love-ce3d8',
    authDomain: 'love-ce3d8.firebaseapp.com',
    databaseURL: 'https://love-ce3d8-default-rtdb.firebaseio.com',
    storageBucket: 'love-ce3d8.appspot.com',
    measurementId: 'G-V4KMLMVWDT',
  );
}